services:
  city:
    build: ./services/city
    ports: ["8001:8000"]
    env_file: [.env, ./services/city/.env.local]
    depends_on: [db]

  public:
    build: ./services/public
    ports: ["8002:8000"]
    env_file: [.env, ./services/public/.env.local]

  data_processing:
    build: ./services/data_processing
    ports: ["8003:8000"]
    env_file: [.env]

  alerts:
    build: ./services/alerts
    ports: ["8004:8000"]
    env_file: [.env]

  accounts:
    build: ./services/accounts
    ports: ["8005:8000"]
    env_file: [.env]

  sensor_data:
    build: ../ExternalSensorData
    environment:
      - API_URL=http://data_processing:8000/api/v1/sensor/ingest
      - MQTT_BROKER=localhost
      - MQTT_PORT=9999
    depends_on:
      - data_processing

  db:
    image: postgres:15
    env_file: [.env]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: