"""
Accounts Agent Service — Pydantic Models
Defines request bodies, response schemas, and internal data-transfer
objects for the full account management and audit logging pipeline.

"""

from __future__ import annotations
 
import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Annotated
 
from pydantic import BaseModel, EmailStr, Field
 
 
# ---------------------------------------------------------------------------
# Enums — values must exactly match the DB CHECK constraints
# ---------------------------------------------------------------------------
 
class UserRole(str, Enum):
    """Matches: ARRAY['City Operator', 'System Administrator', 'Public User']"""
    CITY_OPERATOR        = "City Operator"
    SYSTEM_ADMINISTRATOR = "System Administrator"
    PUBLIC_USER          = "Public User"
 
 
class AuditEventType(str, Enum):
    """Matches the audit_log_data event_type CHECK constraint exactly."""
    USER_LOGIN           = "user_login"
    USER_LOGOUT          = "user_logout"
    USER_CREATED         = "user_created"
    USER_MODIFIED        = "user_modified"
    USER_DELETED         = "user_deleted"
    ALERT_CREATED        = "alert_created"
    ALERT_MODIFIED       = "alert_modified"
    ALERT_DELETED        = "alert_deleted"
    ALERT_TRIGGERED      = "alert_triggered"
    ALERT_ACKNOWLEDGED   = "alert_acknowledged"
    ALERT_VERIFIED       = "alert_verified"
    ALERT_REJECTED       = "alert_rejected"
    DATA_ACCESS          = "data_access"
    API_REQUEST          = "api_request"
    PERMISSION_CHANGE    = "permission_change"
    SYSTEM_EVENT         = "system_event"
    ERROR_EVENT          = "error_event"
 
 
class AuditStatus(str, Enum):
    """Matches: ARRAY['success', 'failure', 'partial']"""
    SUCCESS = "success"
    FAILURE = "failure"
    PARTIAL = "partial"
 
 
class PageMessageType(str, Enum):
    SUCCESS = "success"
    ERROR   = "error"
    INFO    = "info"
 
 
# ---------------------------------------------------------------------------
# AccountInformation schemas
# Maps to the account_information table.
# ---------------------------------------------------------------------------
 
class AccountInfoSchema(BaseModel):
    """
    Internal representation of an AccountInformation record.
    accountinfo_id is a UUID generated by the DB (gen_random_uuid()).
    """
    accountinfo_id: Optional[uuid.UUID] = None   # set by DB on creation
    username:       Annotated[str, Field(example="jsmith")]
    email:          Annotated[EmailStr, Field(example="jsmith@scemas.city")]
    role:           UserRole
    phone_number:   Annotated[Optional[str], Field(example="+1-416-555-0100")]
    is_active:      bool = True
    created_at:     Optional[datetime] = None
    updated_at:     Optional[datetime] = None
    last_login:     Optional[datetime] = None
    # user_id links to Supabase auth.users — set when Supabase Auth is used
    user_id:        Optional[uuid.UUID] = None
 
 
class AccountInfoResponse(BaseModel):
    """Safe account info returned to API callers — no password field."""
    accountinfo_id: uuid.UUID
    username:       str
    email:          str
    role:           UserRole
    phone_number:   Optional[str] = None
    is_active:      bool
    created_at:     Optional[datetime] = None
    last_login:     Optional[datetime] = None
 
 
# ---------------------------------------------------------------------------
# AuditInformation schemas
# Maps to the audit_log_data table (much richer than the original design).
# ---------------------------------------------------------------------------
 
class AuditInformationSchema(BaseModel):
    """
    Mirrors the audit_log_data table columns.
    old_values / new_values store JSONB snapshots of changed fields.
    """
    log_id:           Optional[uuid.UUID] = None   # set by DB
    event_type:       AuditEventType
    action_description: Annotated[str, Field(example="User logged in successfully.")]
    user_id:          Optional[uuid.UUID] = None   # FK to account_information.accountinfo_id
    entity_type:      Annotated[Optional[str], Field(example="account")]
    entity_id:        Annotated[Optional[str], Field(example="user-001")]
    old_values:       Optional[Dict[str, Any]] = None
    new_values:       Optional[Dict[str, Any]] = None
    status:           AuditStatus = AuditStatus.SUCCESS
    ip_address:       Optional[str] = None
    user_agent:       Optional[str] = None
    timestamp:        Optional[datetime] = None    # set by DB default
    retention_until:  Optional[datetime] = None    # set by DB default (now + 1 year)
 
 
# ---------------------------------------------------------------------------
# Login
# ---------------------------------------------------------------------------
 
class LoginRequest(BaseModel):
    username: Annotated[str, Field(example="jsmith")]
    password: Annotated[str, Field(min_length=8, example="SecurePass123!")]
 
 
class LoginResponse(BaseModel):
    success:        bool
    accountinfo_id: Optional[uuid.UUID] = None
    username:       Optional[str] = None
    email:          Optional[str] = None
    role:           Optional[UserRole] = None
    message:        str = ""
    page:           Optional["PageDisplaySchema"] = None
 
 
# ---------------------------------------------------------------------------
# Create account
# ---------------------------------------------------------------------------
 
class CreateAccountRequest(BaseModel):
    username:     Annotated[str     , Field(example="jsmith")]
    password:     Annotated[str     , Field(min_length=8, example="SecurePass123!")]
    email:        Annotated[EmailStr, Field(example="jsmith@scemas.city")]
    phone_number: Annotated[Optional[str], Field(example="+1-416-555-0100")]
    role:         Annotated[UserRole, Field(example=UserRole.CITY_OPERATOR)]
 
 
class CreateAccountResponse(BaseModel):
    success:        bool
    accountinfo_id: Optional[uuid.UUID] = None
    username:       Optional[str] = None
    message:        str = ""
    page:           Optional["PageDisplaySchema"] = None
 
 
# ---------------------------------------------------------------------------
# View account
# ---------------------------------------------------------------------------
 
class ViewAccountResponse(BaseModel):
    account_info: AccountInfoResponse
    page:         Optional["PageDisplaySchema"] = None
 
 
# ---------------------------------------------------------------------------
# Edit account
# ---------------------------------------------------------------------------
 
class EditAccountRequest(BaseModel):
    """All fields optional — only supplied fields are updated."""
    password:     Optional[str]      = Field(None, min_length=8)
    email:        Optional[EmailStr] = None
    phone_number: Optional[str]      = None
 
 
class EditAccountResponse(BaseModel):
    success: bool
    message: str = ""
    page:    Optional["PageDisplaySchema"] = None
 
 
# ---------------------------------------------------------------------------
# Presentation layer page schema
# ---------------------------------------------------------------------------
 
class PageDisplaySchema(BaseModel):
    page_type:    str            # 'login_page', 'create_profile_page', etc.
    message_type: PageMessageType
    message:      str
 
 
# ---------------------------------------------------------------------------
# AccountDatabase update payload (internal — controller use only)
# ---------------------------------------------------------------------------
 
class AccountDatabaseUpdateRequest(BaseModel):
    accountinfo_id: uuid.UUID
    password:       Optional[str]      = None
    email:          Optional[EmailStr] = None
    phone_number:   Optional[str]      = None
 
 
# ---------------------------------------------------------------------------
# Audit log view schemas (AuditLogView interface)
# ---------------------------------------------------------------------------
 
class AuditLogEntryResponse(BaseModel):
    log_id:             uuid.UUID
    event_type:         AuditEventType
    action_description: str
    user_id:            Optional[uuid.UUID] = None
    entity_type:        Optional[str] = None
    entity_id:          Optional[str] = None
    status:             AuditStatus
    ip_address:         Optional[str] = None
    timestamp:          Optional[datetime] = None
 
 
class AuditLogPageResponse(BaseModel):
    entries:   List[AuditLogEntryResponse]
    total:     int
    page:      int = 1
    page_size: int = 20
 
 
# ---------------------------------------------------------------------------
# Generic responses
# ---------------------------------------------------------------------------
 
class SuccessResponse(BaseModel):
    success: bool
    message: str = ""
 
 
class ErrorResponse(BaseModel):
    detail: str
 
 
# Resolve forward references
LoginResponse.model_rebuild()
CreateAccountResponse.model_rebuild()
ViewAccountResponse.model_rebuild()
EditAccountResponse.model_rebuild()
